FROM flink
RUN mkdir -p /opt/flink/usrlib
RUN curl https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka_2.12/1.14.6/flink-connector-kafka_2.12-1.14.6.jar -o /opt/flink/usrlib/flink-connector-kafka_2.12-1.14.6.jar